### ISSUE TITLE
Failed to minify code for production build

### ISSUE THREAD

**Issue by zulhfreelancer** [simonlc/epoch-timeago#3]
Hi,

First of all, thank you for this cool package. It's awesome and I love it.

I'm opening this issue to report the issue with ReactJS. When I ran `$ yarn build` command inside my ReactJS project, I got the following error.

```
$ yarn build
yarn run v1.6.0
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

 	./node_modules/epoch-timeago/index.js:13

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

$ yarn -v
1.6.0

$ npm -v
3.10.3

$ node -v
v6.4.0
```

And this is my package.json file content:

```
{
  "name": "my_react_app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@fortawesome/fontawesome": "^1.1.5",
    "@fortawesome/fontawesome-free-solid": "^5.0.10",
    "@fortawesome/react-fontawesome": "^0.0.18",
    "bootstrap": "3",
    "epoch-timeago": "^1.0.5",
    "react": "^16.3.2",
    "react-bootstrap": "^0.32.1",
    "react-dom": "^16.3.2",
    "react-ellipsis-text": "^1.0.0",
    "react-media": "^1.8.0",
    "react-router-dom": "^4.2.2",
    "react-scripts": "1.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```

Do you have any idea what's wrong here?

I do really appreciate your help and time!

Thank you.

**Comment by simonlc** [comment]
Hi, thank you for posting an issue.

This is because this module does not provide an es5 version, create-react-app still uses an old version of UglifyJS.

When I have time later today I will publish the code to npm with an es5 version and it should fix your issue.

**Comment by zulhfreelancer** [comment]
Thank you!

**Comment by simonlc** [comment]
New package is published with a few build options, you can check out the documentation for how that works. I think with create-react-app there should be no change on your end, and the error should be fixed.

Let me know if it works and feel free to close the issue. Thank you.

**Comment by zulhfreelancer** [comment]
It works now. Thank you. 🙂
